camunda.bpm.admin-user:
  id: diego
  password: portalInterno182

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3310/camunda
    username: root
    password: portalInterno182
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true