server:
  port: 8070

spring:
  application:
    name: configServerLab
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dizanetti/cloud-config-server-lab
          search-paths:
            - ms-partner