### path
@baseUrl = http://localhost:8042/engine-rest

###### TASKS ######

### GET all tasks
GET {{baseUrl}}/task HTTP/1.1

### GET task by id
GET {{baseUrl}}/task/ecedffb1-d215-11ed-b47d-00090ffe0001 HTTP/1.1

### GET task variables by id
GET {{baseUrl}}/task/7694b3e8-e8d8-11ed-b22c-00090ffe0001/variables HTTP/1.1
###### TASKS ######
###### PROCESS DEFINITION ######

### Print Welcome Message
POST {{baseUrl}}/process-definition/key/personal-message/start HTTP/1.1
Content-Type: application/json

{
    "variables": {
        "userName": {
            "value": "diego",
            "type": "String"
        }
    }
}

### Calculate Salary
POST {{baseUrl}}/process-definition/key/calculate-salary/start HTTP/1.1
Content-Type: application/json

{
    "variables": {
        "salary": {
            "value": 1000,
            "type": "Integer"
        },
        "bonus": {
            "value": 15,
            "type":"Integer"
        }
    }
}
###### PROCESS DEFINITION ######
###### USER TASK ######

### Who is it?
POST {{baseUrl}}/process-definition/key/who-is-it/start HTTP/1.1
Content-Type: application/json

{
    "variables": {
        "userName": {
            "value": "diego",
            "type": "String"
        }
    }
}

### Verify User
POST {{baseUrl}}/task/25f650d8-cfab-11ed-a6d6-00090ffe0001/complete HTTP/1.1
Content-Type: application/json

{
    "variables": {
        "userName": {
            "value": "diego",
            "type": "String"
        }
    }
}

### User request Approval Changes
POST {{baseUrl}}/process-definition/key/approval-changes-request/start HTTP/1.1
Content-Type: application/json

{
    "variables": {
        "service": {
            "value": "collaborator",
            "type": "String"
        },
        "collaboratorId": {
            "value": "10",
            "type": "String"
        },
        "userName": {
            "value": "diego",
            "type": "String"
        },
        "addressOld": {
            "value": "Avenida de São Miguel, 85 - Braga",
            "type": "String"
        },
        "addressNew": {
            "value": "Rua Algusta de Sá, 182 - Braga",
            "type": "String"
        }
    }
}

### Analize and approve
POST {{baseUrl}}/task/18aa1660-e90d-11ed-86ba-00090ffe0001/complete HTTP/1.1
Content-Type: application/json

{
    "variables": {
        "service": {
            "value": "collaborator",
            "type": "String"
        },
        "collaboratorId": {
            "value": "10",
            "type": "String"
        },
        "userName": {
            "value": "diego",
            "type": "String"
        },
        "addressOld": {
            "value": "Avenida de São Miguel, 85 - Braga",
            "type": "String"
        },
        "addressNew": {
            "value": "Rua Algusta de Sá, 182 - Braga",
            "type": "String"
        },
        "approved": {
            "value": true,
            "type": "Boolean"
        }
    }
}
###### USER TASK ######